CREATE DATABASE "shortly";

CREATE TABLE "users"(
	"id" SERIAL PRIMARY KEY,
	"name" TEXT NOT NULL,
	"email" TEXT NOT NULL UNIQUE,
	"password" TEXT NOT NULL,
	"createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE TABLE "authTokens"(
	"id" SERIAL PRIMARY KEY,
	"userId" INTEGER UNIQUE REFERENCES "users"("id") NOT NULL,
	"token" TEXT NOT NULL UNIQUE,
	"createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE TABLE "urls"(
	"id" SERIAL PRIMARY KEY,
	"userId" INTEGER REFERENCES "users"("id") NOT NULL,
	"url" TEXT NOT NULL,
	"shortUrl" TEXT NOT NULL,
	"createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE TABLE "visits"(
	"id" SERIAL PRIMARY KEY,
	"urlId" INTEGER NOT NULL REFERENCES "urls"("id"),
	"visitNumber" INTEGER NOT NULL DEFAULT 0
);

